import Brand_guarde from '../../assets/parnter/Brand_guarde.png'
import DriverReach from '../../assets/parnter/DriverReach.png'
import Foster_keeper from '../../assets/parnter/Foster_keeper.png'
import Harverst from '../../assets/parnter/Harverst.png'
import Museminded from '../../assets/parnter/Museminded.png'
import Republic_services from '../../assets/parnter/Republic_services.png'
import Smarter from '../../assets/parnter/Smarter.png'
import Tempo_communications from '../../assets/parnter/Tempo_communications.png'
import Hero_Big_Circle from '../../assets/circle/hero_big_circle.png'
import Hero_Small_Circle from '../../assets/circle/hero_small_circle.png'
import Right_First_Circle from '../../assets/circle/right_first_circle.png'
import Right_Second_Circle from '../../assets/circle/right_second_circle.png'
import Right_Third_Circle from '../../assets/circle/right_third_circle.png'

import agile from '../../assets/WhatDoSucess/agile.png'
import architecture from '../../assets/WhatDoSucess/architecture.png'
import consultation from '../../assets/WhatDoSucess/consultation.png'
import continuous_delivery from '../../assets/WhatDoSucess/continuous_delivery.png'
import hardware_software from '../../assets/WhatDoSucess/hardware_software.png'
import project_management from '../../assets/WhatDoSucess/project_management.png'
import software_monitoring from '../../assets/WhatDoSucess/software_monitoring.png'
import support_maintainance from '../../assets/WhatDoSucess/support_maintainance.png'
import user_experience_design from '../../assets/WhatDoSucess/user-experience-design.png'


import bottom_curve from '../../assets/Our_Process/bottom-curve.png'
import dotted_line_vertical from '../../assets/Our_Process/dotted_line_vertical.png'
import top_curve from '../../assets/Our_Process/top-curve.png'
import vision from '../../assets/Our_Process/vision.png'
import Vision_1 from '../../assets/Our_Process/Vision_1.png'
import Vision_2 from '../../assets/Our_Process/Vision_2.png'
import Vision_3 from '../../assets/Our_Process/Vision_3.png'
import Vision_4 from '../../assets/Our_Process/Vision_4.png'
import Vision_5 from '../../assets/Our_Process/Vision_5.png'

import Images from '../../assets/Images.png'

import Cloud from '../../assets/OurExpertise/Cloud.png'
import Devops from '../../assets/OurExpertise/Devops.png'
import Mobile_Application from '../../assets/OurExpertise/Mobile_Application.png'
import PM from '../../assets/OurExpertise/PM.png'
import Software from '../../assets/OurExpertise/Software.png'
import UX from '../../assets/OurExpertise/UX.png'
import Web_Application from '../../assets/OurExpertise/Web_Application.png'

import About1 from '../../assets/About/About1.png'
import About2 from '../../assets/About/About2.png'
import About3 from '../../assets/About/About3.jpg'
import About4 from '../../assets/About/About4.png'

import agile_architecture from '../../assets/Course/agile_architecture.png'
import consulting from '../../assets/Course/consulting.png'
import continuousdelivery from '../../assets/Course/continuous_delivery.png'
import hardware from '../../assets/Course/hardware.png'
import projectmanagement from '../../assets/Course/project_management.png'
import softwaremonitoring from '../../assets/Course/software_monitoring.png'
import support_maintenance from '../../assets/Course/support_maintenance.png'
import technical_architecture from '../../assets/Course/technical_architecture.png'
import user_experience from '../../assets/Course/user_experience.png'

import tc1 from '../../assets/Trainee/TestimonialCard/1.jpg'
import tc2 from '../../assets/Trainee/TestimonialCard/2.jpg'
import tc3 from '../../assets/Trainee/TestimonialCard/3.jpg'
import tc4 from '../../assets/Trainee/TestimonialCard/4.jpg'
import tc5 from '../../assets/Trainee/TestimonialCard/5.jpg'
import tc6 from '../../assets/Trainee/TestimonialCard/6.jpg'

import Icon1 from '../../assets/Trainee/TraineeBenefit/Icon1.png'
import Icon2 from '../../assets/Trainee/TraineeBenefit/Icon2.png'
import Icon3 from '../../assets/Trainee/TraineeBenefit/Icon3.png'
import Icon4 from '../../assets/Trainee/TraineeBenefit/Icon4.png'
import Icon5 from '../../assets/Trainee/TraineeBenefit/Icon5.png'
import Icon6 from '../../assets/Trainee/TraineeBenefit/Icon6.png'

import Beliefs from '../../assets/Jobs/Beliefs.png'
import JoinOur1 from '../../assets/Jobs/JoinOur1.png'
import JoinOur2 from '../../assets/Jobs/JoinOur2.png'
import JoinOur3 from '../../assets/Jobs/JoinOur3.png'
import Card1 from '../../assets/Jobs/Card1.png'
import Card2 from '../../assets/Jobs/Card2.jpg'
import Cards1 from '../../assets/Jobs/Cards1.png'
import Cards2 from '../../assets/Jobs/Cards2.png'

import Program1 from '../../assets/Trainee/TraineeshipProgram/Program1.jpg'
import Program2 from '../../assets/Trainee/TraineeshipProgram/Program2.jpg'
import Program3 from '../../assets/Trainee/TraineeshipProgram/Program3.jpg'
import Traineeship from '../../assets/Trainee/traineeship.png'

export { Program1, Program2, Program3, Traineeship, Beliefs, JoinOur1, JoinOur2, JoinOur3, Card1, Card2, Cards1, Cards2, Icon1, Icon2, Icon3, Icon4, Icon5, Icon6, tc1, tc2, tc3, tc4, tc5, tc6, agile_architecture, consulting, continuousdelivery, hardware, projectmanagement, softwaremonitoring, support_maintenance, technical_architecture, user_experience, About1, About2, About3, About4, Cloud, Devops, Mobile_Application, PM, Software, UX, Web_Application, Images, bottom_curve, dotted_line_vertical, top_curve, vision, Vision_1, Vision_2, Vision_3, Vision_4, Vision_5, agile, architecture, consultation, continuous_delivery, hardware_software, project_management, software_monitoring, support_maintainance, user_experience_design, Brand_guarde, DriverReach, Foster_keeper, Harverst, Museminded, Republic_services, Smarter, Tempo_communications, Hero_Big_Circle, Hero_Small_Circle, Right_First_Circle, Right_Second_Circle, Right_Third_Circle }