export { default as Header } from './Header/Header'
export { default as Parnter } from './Parnter/Parnter'
export { default as Termional } from './Termional/Termional'
export { default as WhatDoSucess } from './WhatDoSucess/WhatDoSucess'
export { default as Connect } from './Connect/Connect'
export { default as OurProcess } from './OurProcess/OurProcess'
export { default as WhoWeAre } from './WhoWeAre/WhoWeAre'
export { default as Count } from './Count/Count'
