export { default as Header } from './Header/Header'
export { default as Parnter } from './Parnter/Parnter'
export { default as Termional } from './Termional/Termional'
export { default as WhatDoSucess } from './WhatDoSucess/WhatDoSucess'
export { default as Connect } from './Connect/Connect'
export { default as OurProcess } from './OurProcess/OurProcess'
export { default as WhoWeAre } from './WhoWeAre/WhoWeAre'
export { default as Count } from './Count/Count'
export { default as Image } from './Count/Image'
export { default as Course } from './Course/Course'
export { default as ProgramTrainner } from './ProgramTrainner/ProgramTrainner'
export { default as FrequentlyQuestion } from './FrequentlyQuestion/FrequentlyQuestion'
export { default as TraineeCount } from './TraineeCount/TraineeCount'
export { default as TraineeProgram } from './TraineeProgram/TraineeProgram'
export { default as TraineeTestimonials } from './TraineeTestimonials/TraineeTestimonials'
export { default as TraineeBefint } from './TraineeBefint/TraineeBefint'

